taskapp/config/routes.rb
Rails.application.routes.draw do
  resources :projects
  root 'projects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

taskapp/app/models/project.rb
class Project < ApplicationRecord
    validates :title, presence: true
end

taskapp/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

    def index
        @projects = Project.all
    end

    def show
        @project = Project.find(params[:id])
    end

    def new
        @project = Project.new
    end

    def create
        @project = Project.new(project_params)
        @project.save
        redirect_to projects_path
    end

    private
        def project_params
            params[:project].permit(:title)
        end
end

taskapp/app/helpers/projects_helper.rb
module ProjectsHelper
end

taskapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= image_tag "logo.png" %>
    <%= yield %>
    <%= link_to "Home", projects_path %>
  </body>
</html>

taskapp/app/views/projects/index.html.erb
<h1>Projects</h1>

<ul>
    <% @projects.each do |project| %>
    <li><%= link_to project.title, project_path(project.id) %></li>
    <% end %>
</ul>

<p><%= link_to "Add New", new_project_path %></p>

taskapp/app/views/projects/new.html.erb
<h1>Add New</h1>

<%# rails5からform_forは無くなり、form_withに統合された %>
<%# 違いとしては、引数の数と種類が増えた %>
<%# こんな感じ %>
<%# form_with(model: nil, scope: nil, url: nil, format: nil, **options) %>

<%= form_with model: @project do |f| %>
<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
</p>
    <%= f.submit 'save' %>
<p>
</p>
<% end %>

taskapp/app/views/projects/show.html.erb
<h1><%= @project.title %></h1>